---
- name: install the package
  hosts: all
  tasks:
    - name: intsall httpd
      yum:
        name: httpd
        state: latest
    - name: install nfs 
      yum:
        name: nfs-utils
        state: present
    - name: install php
      yum:
        name: php
        state: latest

