---
- name: install the package
  hosts: all
  tasks:
    - name: intsall httpd
      yum:
        name: httpd
        state: latest
    - name: install nfs 
      yum:
        name: nfs-utils
        state: present
    - name: install php
      yum:
        name: php
        state: latest

- name: starte the services
  hosts: all
  vars:
    web_service: httpd
    nfs_service: nfs-server
    firewall_service: firewalld
  tasks:
    - name: starte and enable the {{ web_service }}
      service:
        name: "{{ web_service }}"
        state: started
        enabled: true

